version: '3.7'

services:
  app:
      build:
        context: ..
        dockerfile: .devcontainer/Dockerfile
        args:
          VARIANT: 1.17
          NODE_VERSION: none
      environment:
        PORT: 3010
      ports:
        - 3010:3010
      volumes:
        - ..:/workspace
      user: vscode
      command: sleep infinity

  adminer:
    image: adminer
    restart: always
    ports:
      - 3080:8080

  mysql:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
